In [8]:
#Transpose

In [10]:
import numpy as np

In [11]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
data.shape

(3, 2)

In [13]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
type(data.T)

numpy.ndarray

In [15]:
data.T.shape

(2, 3)

In [16]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
np.transpose(data).shape

(2, 3)

Rotate an array

In [19]:
array2D

NameError: name 'array2D' is not defined

In [20]:
array2D = np.arange(50,100)
array2D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
array2D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
array2D.shape

(50,)

In [24]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
data.max()

6

In [26]:
np.max(data)

6

In [27]:
data.min(), np.min(data)

(1, 1)

In [28]:
data.sum()

21

In [29]:
np.sum(data)

21

In [30]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
data[0].max(), data[1].max()

(2, 4)

In [32]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
data.max()

6

In [34]:
data.max(axis = 0)

array([5, 6])

In [35]:
data.max(axis = 1)

array([2, 4, 6])

In [36]:
data.min(axis = 0)

array([1, 2])

In [37]:
data.sum(axis = 1)

array([ 3,  7, 11])

In [43]:
array2D 

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
#mean, median, variance, sd

In [45]:
np.mean(array2D)

74.5

In [46]:
np.median(array2D)

74.5

In [47]:
np.var(array2D)

208.25

In [48]:
np.std(array2D)

14.430869689661812

In [50]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
c = np.arange(1,7).reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.hstack((a,c))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [57]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

Splitting of arrays

In [60]:
d = np.arange(1,25).reshape(4,6)
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [62]:
np.hsplit(d,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [63]:
np.vsplit(d,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [64]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [72]:
np.concatenate((a,c), axis = 1)

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [73]:
np.append(a,c)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6])

In [74]:
np.append(b,c)

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6])

In [75]:
np.append(a,c, axis=1) #some hstack

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [79]:
np.append(b,c)

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6])

Updating with arrar

In [81]:
e = np.arange(50,80).reshape(5,6)
e

array([[50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73],
       [74, 75, 76, 77, 78, 79]])

In [84]:
f = np.arange(60, 90).reshape(5,6)
f

array([[60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89]])

In [85]:
np.where(e%2==0, 1, 0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [86]:
np.where(e%2==0, True,False)

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

set opertion on array

In [87]:
e

array([[50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73],
       [74, 75, 76, 77, 78, 79]])

In [88]:
f

array([[60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89]])

In [89]:
np.union1d(e,f)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89])

In [90]:
np.intersect1d(e,f)

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [91]:
np.setdiff1d(e,f)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

Arithmetic Operation on Arrays

In [92]:
data = np.array([1,2])
data

array([1, 2])

In [93]:
ones = np.ones(2, dtype=int)
ones

array([1, 1])

In [94]:
data +ones

array([2, 3])

In [95]:
data-ones

array([0, 1])

In [96]:
data*ones

array([1, 2])

In [97]:
data / ones

array([1., 2.])

In [98]:
data

array([1, 2])

In [99]:
data + 1

array([2, 3])

In [100]:
data + 3

array([4, 5])

In [102]:
np.arange(3)

array([0, 1, 2])

In [103]:
np.arange(3)+5

array([5, 6, 7])

In [104]:
np.ones((3,3), dtype= int) +np.arange(3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [106]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Filtering Arrays

In [108]:
age = np.array([10,20,30,40,50,60,70,80])
age

array([10, 20, 30, 40, 50, 60, 70, 80])

In [109]:
age>60

array([False, False, False, False, False, False,  True,  True])

In [110]:
age[age > 60]

array([70, 80])

In [111]:
age[(age >=10) & (age <=50)]

array([10, 20, 30, 40, 50])

Expanding a numpy array

In [112]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [113]:
a.ndim

1

In [114]:
a.shape

(4,)

In [115]:
a.shape

(4,)

In [117]:
b = np.array([[1,2,3,4]]) 
b

array([[1, 2, 3, 4]])

In [118]:
b.ndim

2

In [119]:
b.shape

(1, 4)

In [121]:
c.ndim

2

In [122]:
c.shape

(3, 2)

In [123]:
a

array([1, 2, 3, 4])

In [126]:
b1 = np.expand_dims(a, axis = 0)
b1

array([[1, 2, 3, 4]])

In [128]:
b1.ndim

2

In [129]:
b1.shape

(1, 4)

squeezing a numpy array

In [130]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
a.shape

(3, 2)

In [132]:
a.ndim

2

In [134]:
b = np.squeeze(a)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [135]:
b.shape

(3, 2)

In [137]:
b.ndim

2

In [138]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [139]:
c = np.array([1,2])
c

array([1, 2])

In [140]:
np.isin(a,c)

array([ True,  True, False])

In [141]:
np.isin(a, [4,5,6])

array([False, False, False])

In [142]:
np.isin(a, [4,5,1])

array([ True, False, False])

In [144]:
np.isin(a, [4,2,1])

array([ True,  True, False])

Mathematics Function

.floor
.Cell
.round

In [145]:
np.floor(3.557)

3.0

In [146]:
np.ceil(3.527)

4.0

In [147]:
np.round(3.527)

4.0