In [2]:
#pip install pandas

In [3]:
import pandas as pd

In [4]:
pd.__version__

'1.3.4'

In [5]:
import numpy as np

In [6]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [7]:
type(a)

numpy.ndarray

In [8]:
b = pd.Series(a)
print(b)

0    10
1    20
2    30
3    40
dtype: int64


In [9]:
type(b)

pandas.core.series.Series

In [10]:
b = pd.Series([10,20,30,40])
b

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
l = [10,20,30,40,50]
l1 = ['a','b','c','d','e']
b = pd.Series(l, index = l1)
print(b)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [12]:
b.values

array([10, 20, 30, 40, 50])

In [13]:
b['a'], b['e']

(10, 50)

In [14]:
b[0], b[1]

(10, 20)

In [15]:
'a', a

('a', array([10, 20, 30, 40]))

In [16]:
a = 5

In [17]:
a

5

In [18]:
'a'

'a'

In [19]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
b.values

array([10, 20, 30, 40, 50])

In [21]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [22]:
b[0], b[1],b[2],b[3]

(10, 20, 30, 40)

In [23]:
d = {'a':10, 'b':20}
d

{'a': 10, 'b': 20}

In [24]:
d.keys()

dict_keys(['a', 'b'])

In [25]:
type(b)

pandas.core.series.Series

In [26]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [27]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [28]:
b.values

array([10, 20, 30, 40, 50])

In [29]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [30]:
b['a'], b['e'] #accessing using label

(10, 50)

In [31]:
b[0]

10

In [32]:
a

5

In [33]:
'a', a

('a', 5)

# Creating a series with a dictionary

In [34]:
d = {'a':10, 'b':20}
d

{'a': 10, 'b': 20}

In [35]:
d.keys()

dict_keys(['a', 'b'])

In [36]:
d.values()

dict_values([10, 20])

In [37]:
e = pd.Series(d)
e

a    10
b    20
dtype: int64

# Creating  a stories of typedatetime

In [38]:
dates_series = pd.date_range(start='11-09-2017',end='12-12-2017')
dates_series

DatetimeIndex(['2017-11-09', '2017-11-10', '2017-11-11', '2017-11-12',
               '2017-11-13', '2017-11-14', '2017-11-15', '2017-11-16',
               '2017-11-17', '2017-11-18', '2017-11-19', '2017-11-20',
               '2017-11-21', '2017-11-22', '2017-11-23', '2017-11-24',
               '2017-11-25', '2017-11-26', '2017-11-27', '2017-11-28',
               '2017-11-29', '2017-11-30', '2017-12-01', '2017-12-02',
               '2017-12-03', '2017-12-04', '2017-12-05', '2017-12-06',
               '2017-12-07', '2017-12-08', '2017-12-09', '2017-12-10',
               '2017-12-11', '2017-12-12'],
              dtype='datetime64[ns]', freq='D')

# Indexing series

In [39]:
l = [10,20,30,40,50,60]

In [40]:
l[0]

10

In [41]:
s = pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [42]:
s[0]

10

In [43]:
s[2]

30

In [44]:
s[2:]

2    30
3    40
4    50
5    60
dtype: int64

In [45]:
s = pd.Series(dtype='object')
s

Series([], dtype: object)

# Creating dataframe from  dictionary

In [46]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

Differnt DataFrame using Dictonary

In [47]:
data = {
    'Name' : ['ajay','atul', 'arun', 'raj'],
    'Age' :  [24,25,26,64]
}
data

{'Name': ['ajay', 'atul', 'arun', 'raj'], 'Age': [24, 25, 26, 64]}

In [48]:
df = pd.DataFrame(data)
df

Name  Age
0  ajay   24
1  atul   25
2  arun   26
3   raj   64

In [49]:
data = {
    'col1' : ['items1', 'item2', 'item3', 'item4'],
    'col2' : ['items1', 'item2', 'item3', 'item4'],
    'col3' : ['items1', 'item2', 'item3', 'item4'],
    'col4' : ['items1', 'item2', 'item3', 'item4']
    
}
data



{'col1': ['items1', 'item2', 'item3', 'item4'],
 'col2': ['items1', 'item2', 'item3', 'item4'],
 'col3': ['items1', 'item2', 'item3', 'item4'],
 'col4': ['items1', 'item2', 'item3', 'item4']}

In [50]:
df = pd.DataFrame(data)
df

col1    col2    col3    col4
0  items1  items1  items1  items1
1   item2   item2   item2   item2
2   item3   item3   item3   item3
3   item4   item4   item4   item4

In [51]:
sample_df = pd.DataFrame(data)
df

col1    col2    col3    col4
0  items1  items1  items1  items1
1   item2   item2   item2   item2
2   item3   item3   item3   item3
3   item4   item4   item4   item4

Info

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      object
 1   col2    4 non-null      object
 2   col3    4 non-null      object
 3   col4    4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes


In [53]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      object
 1   col2    4 non-null      object
 2   col3    4 non-null      object
 3   col4    4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes


In [54]:
type(sample_df)

pandas.core.frame.DataFrame

# Creating DataFrame using Tuple

In [55]:
data = [
    ('1/1/2019',23,6,'Rain'),
    ('2/1/2019',11,7,'Fog'),
    ('3/1/2019',26,8,'sunny'),
    ('4/1/2019',13,9,'snow')
]
data

[('1/1/2019', 23, 6, 'Rain'),
 ('2/1/2019', 11, 7, 'Fog'),
 ('3/1/2019', 26, 8, 'sunny'),
 ('4/1/2019', 13, 9, 'snow')]

In [56]:
df = pd.DataFrame(data)
df

0   1  2      3
0  1/1/2019  23  6   Rain
1  2/1/2019  11  7    Fog
2  3/1/2019  26  8  sunny
3  4/1/2019  13  9   snow

In [57]:
df = pd.DataFrame(data, columns=['Day', 'Temperature', 'Windspeed','Event'])
df

Day  Temperature  Windspeed  Event
0  1/1/2019           23          6   Rain
1  2/1/2019           11          7    Fog
2  3/1/2019           26          8  sunny
3  4/1/2019           13          9   snow

In [58]:
df.T

0         1         2         3
Day          1/1/2019  2/1/2019  3/1/2019  4/1/2019
Temperature        23        11        26        13
Windspeed           6         7         8         9
Event            Rain       Fog     sunny      snow

In [59]:
df

Day  Temperature  Windspeed  Event
0  1/1/2019           23          6   Rain
1  2/1/2019           11          7    Fog
2  3/1/2019           26          8  sunny
3  4/1/2019           13          9   snow

In [60]:
df.T

0         1         2         3
Day          1/1/2019  2/1/2019  3/1/2019  4/1/2019
Temperature        23        11        26        13
Windspeed           6         7         8         9
Event            Rain       Fog     sunny      snow

In [61]:
df.dtypes

Day            object
Temperature     int64
Windspeed       int64
Event          object
dtype: object

In [62]:
df.columns

Index(['Day', 'Temperature', 'Windspeed', 'Event'], dtype='object')

In [63]:
df = pd.DataFrame(data, columns=['Day', 'Temperature', 'Windspeed','Event'], index=['a','b','c','d'])
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [64]:
df.shape

(4, 4)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          4 non-null      object
 1   Temperature  4 non-null      int64 
 2   Windspeed    4 non-null      int64 
 3   Event        4 non-null      object
dtypes: int64(2), object(2)
memory usage: 160.0+ bytes


# head-by default head return first 5row

In [66]:
df.head()

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [67]:
df.head(3)

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny

In [68]:
df.tail(3)

Day  Temperature  Windspeed  Event
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

Statistics

In [69]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [70]:
df['Day']

a    1/1/2019
b    2/1/2019
c    3/1/2019
d    4/1/2019
Name: Day, dtype: object

In [71]:
df['Event']

a     Rain
b      Fog
c    sunny
d     snow
Name: Event, dtype: object

In [72]:
df[['Day', 'Event']]

Day  Event
a  1/1/2019   Rain
b  2/1/2019    Fog
c  3/1/2019  sunny
d  4/1/2019   snow

In [73]:
df['Temperature']

a    23
b    11
c    26
d    13
Name: Temperature, dtype: int64

In [74]:
type(df['Temperature'])

pandas.core.series.Series

In [75]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [76]:
df.sum()

Day            1/1/20192/1/20193/1/20194/1/2019
Temperature                                  73
Windspeed                                    30
Event                          RainFogsunnysnow
dtype: object

# axis 1-row wise sum

In [77]:
df.sum(axis = 0)

Day            1/1/20192/1/20193/1/20194/1/2019
Temperature                                  73
Windspeed                                    30
Event                          RainFogsunnysnow
dtype: object

In [78]:
df.sum()

Day            1/1/20192/1/20193/1/20194/1/2019
Temperature                                  73
Windspeed                                    30
Event                          RainFogsunnysnow
dtype: object

In [79]:
df.sum(axis = 1,numeric_only=True)

a    29
b    18
c    34
d    22
dtype: int64

In [80]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [81]:
df['Temperature'].sum()

73

# Mean

In [82]:
df.mean(numeric_only=True)

Temperature    18.25
Windspeed       7.50
dtype: float64

In [83]:
df['Temperature'].mean()

18.25

In [84]:
df['Windspeed'].mean()

7.5

# median

In [85]:
df.median(numeric_only=True)

Temperature    18.0
Windspeed       7.5
dtype: float64

In [86]:
df['Temperature'].median()

18.0

# std()

In [87]:
df.std(numeric_only=True)

Temperature    7.365460
Windspeed      1.290994
dtype: float64

In [88]:
df.std(numeric_only=True)

Temperature    7.365460
Windspeed      1.290994
dtype: float64

# describe()-summary of the data 

In [89]:
df.describe()

Temperature  Windspeed
count      4.00000   4.000000
mean      18.25000   7.500000
std        7.36546   1.290994
min       11.00000   6.000000
25%       12.50000   6.750000
50%       18.00000   7.500000
75%       23.75000   8.250000
max       26.00000   9.000000

# max-return the maximum values

In [90]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [91]:
df.max()

Day            4/1/2019
Temperature          26
Windspeed             9
Event             sunny
dtype: object

In [92]:
df['Temperature'].max()

26

min-return the minimum values

In [93]:
df.min()

Day            1/1/2019
Temperature          11
Windspeed             6
Event               Fog
dtype: object

In [94]:
df['Temperature'].min()

11

# Working with .csv

In [96]:
df = pd.read_csv('/Users/yuvarajyadav/MyWork/DL/Data-Science/csv/iris.csv')
df

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [97]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [98]:
df.tail()

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [99]:
df.shape

(150, 5)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [101]:
df.describe()

SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [102]:
df['Name'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [103]:
df['Name'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Name, dtype: int64

In [104]:
df.dtypes

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Name            object
dtype: object

In [106]:
weather_df = pd.read_csv('/Users/yuvarajyadav/MyWork/DL/Data-Science/csv/nyc.csv')
weather_df

Unnamed: 0        Date  Max.TemperatureF  Mean.TemperatureF  \
0               1  1948-07-01                84               78.0   
1               2  1948-07-02                82               72.0   
2               3  1948-07-03                78               71.0   
3               4  1948-07-04                84               76.0   
4               5  1948-07-05                93               82.0   
...           ...         ...               ...                ...   
24555       24623  2015-12-27                63               56.0   
24556       24624  2015-12-28                48               42.0   
24557       24625  2015-12-29                49               42.0   
24558       24626  2015-12-30                51               46.0   
24559       24627  2015-12-31                52               48.0   

       Min.TemperatureF  Max.Dew.PointF  MeanDew.PointF  Min.DewpointF  \
0                    72              71              65             58   
1                    63              62              53             49   
2                    64              66              58             53   
3                    68              68              63             56   
4                    70              74              69             65   
...                 ...             ...             ...            ...   
24555                48              58              51             37   
24556                35              35              25             19   
24557                34              46              40             30   
24558                41              48              41             37   
24559                43              46              38             27   

       Max.Humidity  Mean.Humidity  ...  Min.VisibilityMiles  \
0                93             65  ...                  2.0   
1                76             51  ...                 10.0   
2                84             62  ...                  5.0   
3                90             67  ...                  2.0   
4                93             71  ...                  3.0   
...             ...            ...  ...                  ...   
24555            96             82  ...                  0.0   
24556            70             57  ...                  6.0   
24557            93             88  ...                  1.0   
24558            93             85  ...                  2.0   
24559            93             71  ...                  5.0   

       Max.Wind.SpeedMPH  Mean.Wind.SpeedMPH  Max.Gust.SpeedMPH  \
0                     16                   8                NaN   
1                     16                  10                NaN   
2                     14                   6                NaN   
3                     12                   5                NaN   
4                     18                   8                NaN   
...                  ...                 ...                ...   
24555                 23                  12               29.0   
24556                 23                  14               37.0   
24557                 24                  12               30.0   
24558                 22                   7               26.0   
24559                 20                  12               25.0   

       PrecipitationIn  CloudCover                 Events  \
0                 0.00         0.0                    Fog   
1                 0.00         0.0                    NaN   
2                 0.00         0.0                    NaN   
3                 0.00         0.0                    Fog   
4                 0.00         0.0  Fog-Rain-Thunderstorm   
...                ...         ...                    ...   
24555             0.08         8.0               Fog-Rain   
24556             0.05         7.0              Rain-Snow   
24557             0.66         8.0              Rain-Snow   
24558             0.37         8.0                   Rain   
24559             0.06         7