In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [4]:
pd.__version__

'1.4.4'

In [5]:
import numpy as np

In [8]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [9]:
type(a)

numpy.ndarray

In [11]:
print(a)

[10 20 30 40]


In [26]:
import pandas as pd

In [27]:
pd.__version__

'1.4.4'

In [29]:
print(a)

[10 20 30 40]


In [31]:
b = pd.series(a)
b

AttributeError: module 'pandas' has no attribute 'series'

creating a numeric pandas series

In [32]:
import pandas

mydataset = {
    'cars' : ["BMW", "volvo","Ford"],
    'passing' : [3,7,2]

}

myvar = pandas.dataFrame(mydataset)

print(myvar)

AttributeError: module 'pandas' has no attribute 'dataFrame'