In [214]:
#pip install pandas

In [215]:
import pandas as pd

In [216]:
pd.__version__

'1.4.4'

In [217]:
import numpy as np

In [218]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [219]:
type(a)

numpy.ndarray

In [220]:
b = pd.Series(a)
print(b)

0    10
1    20
2    30
3    40
dtype: int32


In [221]:
type(b)

pandas.core.series.Series

In [222]:
b = pd.Series([10,20,30,40])
b

0    10
1    20
2    30
3    40
dtype: int64

In [223]:
l = [10,20,30,40,50]
l1 = ['a','b','c','d','e']
b = pd.Series(l, index = l1)
print(b)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [224]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [225]:
b['a'], b['e']

(10, 50)

In [226]:
b[0], b[1]

(10, 20)

In [227]:
'a', a

('a', array([10, 20, 30, 40]))

In [228]:
a = 5

In [229]:
a

5

In [230]:
'a'

'a'

In [231]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [232]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [233]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [234]:
b[0], b[1],b[2],b[3]

(10, 20, 30, 40)

In [235]:
d = {'a':10, 'b':20}
d

{'a': 10, 'b': 20}

In [236]:
d.keys()

dict_keys(['a', 'b'])

In [237]:
type(b)

pandas.core.series.Series

In [238]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [239]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [240]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [241]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [242]:
b['a'], b['e'] #accessing using label

(10, 50)

In [243]:
b[0]

10

In [244]:
a

5

In [245]:
'a', a

('a', 5)

# Creating a series with a dictionary

In [246]:
d = {'a':10, 'b':20}
d

{'a': 10, 'b': 20}

In [247]:
d.keys()

dict_keys(['a', 'b'])

In [248]:
d.values()

dict_values([10, 20])

In [249]:
e = pd.Series(d)
e

a    10
b    20
dtype: int64

# Creating  a stories of typedatetime

In [250]:
dates_series = pd.date_range(start='11-09-2017',end='12-12-2017')
dates_series

DatetimeIndex(['2017-11-09', '2017-11-10', '2017-11-11', '2017-11-12',
               '2017-11-13', '2017-11-14', '2017-11-15', '2017-11-16',
               '2017-11-17', '2017-11-18', '2017-11-19', '2017-11-20',
               '2017-11-21', '2017-11-22', '2017-11-23', '2017-11-24',
               '2017-11-25', '2017-11-26', '2017-11-27', '2017-11-28',
               '2017-11-29', '2017-11-30', '2017-12-01', '2017-12-02',
               '2017-12-03', '2017-12-04', '2017-12-05', '2017-12-06',
               '2017-12-07', '2017-12-08', '2017-12-09', '2017-12-10',
               '2017-12-11', '2017-12-12'],
              dtype='datetime64[ns]', freq='D')

# Indexing series

In [251]:
l = [10,20,30,40,50,60]

In [252]:
l[0]

10

In [253]:
s = pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [254]:
s[0]

10

In [255]:
s[2]

30

In [256]:
s[2:]

2    30
3    40
4    50
5    60
dtype: int64

In [257]:
s = pd.Series(dtype='object')
s

Series([], dtype: object)

# Creating dataframe from  dictionary

In [258]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

Differnt DataFrame using Dictonary

In [259]:
data = {
    'Name' : ['ajay','atul', 'arun', 'raj'],
    'Age' :  [24,25,26,64]
}
data

{'Name': ['ajay', 'atul', 'arun', 'raj'], 'Age': [24, 25, 26, 64]}

In [260]:
df = pd.DataFrame(data)
df

Name  Age
0  ajay   24
1  atul   25
2  arun   26
3   raj   64

In [261]:
data = {
    'col1' : ['items1', 'item2', 'item3', 'item4'],
    'col2' : ['items1', 'item2', 'item3', 'item4'],
    'col3' : ['items1', 'item2', 'item3', 'item4'],
    'col4' : ['items1', 'item2', 'item3', 'item4']
    
}
data



{'col1': ['items1', 'item2', 'item3', 'item4'],
 'col2': ['items1', 'item2', 'item3', 'item4'],
 'col3': ['items1', 'item2', 'item3', 'item4'],
 'col4': ['items1', 'item2', 'item3', 'item4']}

In [262]:
df = pd.DataFrame(data)
df

col1    col2    col3    col4
0  items1  items1  items1  items1
1   item2   item2   item2   item2
2   item3   item3   item3   item3
3   item4   item4   item4   item4

In [263]:
sample_df = pd.DataFrame(data)
df

col1    col2    col3    col4
0  items1  items1  items1  items1
1   item2   item2   item2   item2
2   item3   item3   item3   item3
3   item4   item4   item4   item4

Info

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      object
 1   col2    4 non-null      object
 2   col3    4 non-null      object
 3   col4    4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes


In [265]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      object
 1   col2    4 non-null      object
 2   col3    4 non-null      object
 3   col4    4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes


In [266]:
type(sample_df)

pandas.core.frame.DataFrame

# Creating DataFrame using Tuple

In [267]:
data = [
    ('1/1/2019',23,6,'Rain'),
    ('2/1/2019',11,7,'Fog'),
    ('3/1/2019',26,8,'sunny'),
    ('4/1/2019',13,9,'snow')
]
data

[('1/1/2019', 23, 6, 'Rain'),
 ('2/1/2019', 11, 7, 'Fog'),
 ('3/1/2019', 26, 8, 'sunny'),
 ('4/1/2019', 13, 9, 'snow')]

In [268]:
df = pd.DataFrame(data)
df

0   1  2      3
0  1/1/2019  23  6   Rain
1  2/1/2019  11  7    Fog
2  3/1/2019  26  8  sunny
3  4/1/2019  13  9   snow

In [269]:
df = pd.DataFrame(data, columns=['Day', 'Temperature', 'Windspeed','Event'])
df

Day  Temperature  Windspeed  Event
0  1/1/2019           23          6   Rain
1  2/1/2019           11          7    Fog
2  3/1/2019           26          8  sunny
3  4/1/2019           13          9   snow

In [270]:
df.T

0         1         2         3
Day          1/1/2019  2/1/2019  3/1/2019  4/1/2019
Temperature        23        11        26        13
Windspeed           6         7         8         9
Event            Rain       Fog     sunny      snow

In [271]:
df

Day  Temperature  Windspeed  Event
0  1/1/2019           23          6   Rain
1  2/1/2019           11          7    Fog
2  3/1/2019           26          8  sunny
3  4/1/2019           13          9   snow

In [272]:
df.T

0         1         2         3
Day          1/1/2019  2/1/2019  3/1/2019  4/1/2019
Temperature        23        11        26        13
Windspeed           6         7         8         9
Event            Rain       Fog     sunny      snow

In [273]:
df.dtypes

Day            object
Temperature     int64
Windspeed       int64
Event          object
dtype: object

In [274]:
df.columns

Index(['Day', 'Temperature', 'Windspeed', 'Event'], dtype='object')

In [275]:
df = pd.DataFrame(data, columns=['Day', 'Temperature', 'Windspeed','Event'], index=['a','b','c','d'])
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [276]:
df.shape

(4, 4)

In [277]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          4 non-null      object
 1   Temperature  4 non-null      int64 
 2   Windspeed    4 non-null      int64 
 3   Event        4 non-null      object
dtypes: int64(2), object(2)
memory usage: 160.0+ bytes


# head-by default head return first 5row

In [278]:
df.head()

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [279]:
df.head(3)

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny

In [280]:
df.tail(3)

Day  Temperature  Windspeed  Event
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

Statistics

In [281]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [282]:
df['Day']

a    1/1/2019
b    2/1/2019
c    3/1/2019
d    4/1/2019
Name: Day, dtype: object

In [283]:
df['Event']

a     Rain
b      Fog
c    sunny
d     snow
Name: Event, dtype: object

In [284]:
df[['Day', 'Event']]

Day  Event
a  1/1/2019   Rain
b  2/1/2019    Fog
c  3/1/2019  sunny
d  4/1/2019   snow

In [285]:
df['Temperature']

a    23
b    11
c    26
d    13
Name: Temperature, dtype: int64

In [286]:
type(df['Temperature'])

pandas.core.series.Series

In [287]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [288]:
df.sum()

Day            1/1/20192/1/20193/1/20194/1/2019
Temperature                                  73
Windspeed                                    30
Event                          RainFogsunnysnow
dtype: object

# axis 1-row wise sum

In [289]:
df.sum(axis = 0)

Day            1/1/20192/1/20193/1/20194/1/2019
Temperature                                  73
Windspeed                                    30
Event                          RainFogsunnysnow
dtype: object

In [290]:
df.sum()

Day            1/1/20192/1/20193/1/20194/1/2019
Temperature                                  73
Windspeed                                    30
Event                          RainFogsunnysnow
dtype: object

In [291]:
df.sum(axis = 1,numeric_only=True)

a    29
b    18
c    34
d    22
dtype: int64

In [292]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [293]:
df['Temperature'].sum()

73

# Mean

In [294]:
df.mean(numeric_only=True)

Temperature    18.25
Windspeed       7.50
dtype: float64

In [295]:
df['Temperature'].mean()

18.25

In [296]:
df['Windspeed'].mean()

7.5

# median

In [297]:
df.median(numeric_only=True)

Temperature    18.0
Windspeed       7.5
dtype: float64

In [298]:
df['Temperature'].median()

18.0

# std()

In [299]:
df.std(numeric_only=True)

Temperature    7.365460
Windspeed      1.290994
dtype: float64

In [300]:
df.std(numeric_only=True)

Temperature    7.365460
Windspeed      1.290994
dtype: float64

# describe()-summary of the data 

In [301]:
df.describe()

Temperature  Windspeed
count      4.00000   4.000000
mean      18.25000   7.500000
std        7.36546   1.290994
min       11.00000   6.000000
25%       12.50000   6.750000
50%       18.00000   7.500000
75%       23.75000   8.250000
max       26.00000   9.000000

# max-return the maximum values

In [302]:
df

Day  Temperature  Windspeed  Event
a  1/1/2019           23          6   Rain
b  2/1/2019           11          7    Fog
c  3/1/2019           26          8  sunny
d  4/1/2019           13          9   snow

In [303]:
df.max()

Day            4/1/2019
Temperature          26
Windspeed             9
Event             sunny
dtype: object

In [304]:
df['Temperature'].max()

26

min-return the minimum values

In [305]:
df.min()

Day            1/1/2019
Temperature          11
Windspeed             6
Event               Fog
dtype: object

In [306]:
df['Temperature'].min()

11

# Working with .csv

In [307]:
df = pd.read_csv('D:\Sandhya\Data-Science\csv\iris.csv')
df

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [308]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [309]:
df.tail()

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [310]:
df.shape

(150, 5)

In [311]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [312]:
df.describe()

SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [313]:
df['Name'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [314]:
df['Name'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Name, dtype: int64

In [315]:
df.dtypes

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Name            object
dtype: object

# Weather Dataset

In [316]:
#weather_df = pd.read_excel('weather_data.xlsx')
#weather_df.head()

In [319]:
weather_df = pd.read_csv('D:\Sandhya\Data-Science\csv\nyc.csv')
weather_df.head()

OSError: [Errno 22] Invalid argument: 'D:\\Sandhya\\Data-Science\\csv\nyc.csv'