In [1]:
#pip install pandas

In [10]:
import pandas as pd

In [3]:
pd.__version__

'1.4.4'

In [4]:
import numpy as np

In [5]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [6]:
type(a)

numpy.ndarray

In [12]:
b = pd.Series(a)
print(b)

0    10
1    20
2    30
3    40
dtype: int32


In [13]:
type(b)

pandas.core.series.Series

In [15]:
b = pd.Series([10,20,30,40])
b

0    10
1    20
2    30
3    40
dtype: int64

In [17]:
l = [10,20,30,40,50]
l1 = ['a','b','c','d','e']
b = pd.Series(l, index = l1)
print(b)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [18]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [20]:
b['a'], b['e']

(10, 50)

In [21]:
b[0], b[1]

(10, 20)

In [22]:
'a', a

('a', array([10, 20, 30, 40]))

In [23]:
a = 5

In [24]:
a

5

In [25]:
'a'

'a'

In [26]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [27]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [28]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [30]:
b[0], b[1],b[2],b[3]

(10, 20, 30, 40)

In [32]:
d = {'a':10, 'b':20}
d

{'a': 10, 'b': 20}

In [33]:
d.keys()

dict_keys(['a', 'b'])

Creating a series with a dictionary

In [ ]:
dates_Series = pd.date_range