In [1]:
arr2d = np.array([[10,20,30], [40,50,60]])

NameError: name 'np' is not defined

In [3]:
#import numpy

In [7]:
#print(np.__version__)

In [4]:
import numpy as np

In [9]:
print(np.__version__)

1.21.5


In [12]:
l =[1,2,3,4]
l

[1, 2, 3, 4]

In [13]:
l,type(l)

([1, 2, 3, 4], list)

In [15]:
l = [1,2,3,4]
arr = np.array(l)

In [16]:
l, type(l)

([1, 2, 3, 4], list)

In [17]:
arr

array([1, 2, 3, 4])

In [18]:
type(arr)

numpy.ndarray

In [20]:
arr = np.array((4,5,6))
arr

array([4, 5, 6])

In [21]:
arr.shape

(3,)

In [22]:
arr2d = np.array([[10,20,30],[40,50,60]])

In [23]:
#list of list : [[10,20,30], [40,50,60]]

In [24]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [25]:
arr2d.shape

(2, 3)

In [27]:
arr3d = np.array([[[10,20,30], [40,50,60],[70,80,90]]])
arr3d

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [28]:
arr3d.shape

(1, 3, 3)

arrayname.ndim

In [30]:
arr3d

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [31]:
arr.ndim

1

In [32]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
arr1d = np.array(range(1,10,2))
arr1d

array([1, 3, 5, 7, 9])

In [36]:
arr1d.ndim

1

In [37]:
arr1d.dtype

dtype('int32')

In [39]:
arr1d.dtype

dtype('int32')

In [42]:
arr1d = np.array([4.5,5,139.45])
arr1d

array([  4.5 ,   5.  , 139.45])

In [43]:
arr1d.dtype

dtype('float64')

In [45]:
arr1d = np.array([12,4.5,'hari', True])
arr1d

array(['12', '4.5', 'hari', 'True'], dtype='<U32')

arrayname

In [47]:
arr1d = np.array(range(1,10,2))
arr1d

array([1, 3, 5, 7, 9])

In [48]:
arr1d

array([1, 3, 5, 7, 9])

In [50]:
arr1d = np.array(range(1,10))
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr1d.size

9

In [52]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

Type(arrayname)

In [54]:
l = [1,2,3]
type(l)

list

In [55]:
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
type(arr1d)

numpy.ndarray

In [57]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [60]:
a = [2,3,4,5,6]
a

[2, 3, 4, 5, 6]

In [62]:
a = np.array([2,3,4,5,6])
a

array([2, 3, 4, 5, 6])

In [63]:
a**2

array([ 4,  9, 16, 25, 36], dtype=int32)

In [64]:
a

array([2, 3, 4, 5, 6])

In [65]:
a+1

array([3, 4, 5, 6, 7])

In [66]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [67]:
data.shape

(6,)

In [68]:
data.ndim

1

In [70]:
arr = data.reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr.shape

(2, 3)

In [72]:
arr.ndim

2

In [74]:
arr = data.reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
arr.shape

(3, 2)

In [76]:
arr.ndim

2

In [77]:
arr = np.array(range(1,9))

print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5 6 7 8]
(8,)
1


In [81]:
arr2d = arr.reshape(2,4)

print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [82]:
arr3d = arr.reshape(3,3)

print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [83]:
range(5)

range(0, 5)

In [84]:
list(range(5))

[0, 1, 2, 3, 4]

In [85]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [86]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [87]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [89]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [90]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [93]:
np.arange(1,10).reshape(3,3).ndim

2

In [94]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.arange(1,10).reshape(3,3).shape

(3, 3)

Array with linspace()

In [97]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [98]:
np.linspace(10,12,4)

array([10.        , 10.66666667, 11.33333333, 12.        ])

ZeroArray

In [101]:
np.zeros(3)

array([0., 0., 0.])

In [102]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

One array

In [103]:
np.ones(3,)

array([1., 1., 1.])

In [104]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Full Array

In [108]:
np.full((3),5)

array([5, 5, 5])

In [109]:
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [110]:
np.full((2,4,5),10)

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]])

EYE Array

In [111]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [115]:
np.diag(arr)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

PYTHON BUILT IN RANDOM MODULE

In [2]:
import random

In [3]:
# generate rand num between 0 to 1
random.random()

0.608551725211912

In [8]:
random.randint(1,10)

10

In [9]:
random.randint(1,100)

82

In [ ]:
seed

In [10]:
random.seed(10)
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))

10
1
7
8


In [11]:
random.seed(100)
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))

3
8
8
3


In [12]:
random.seed(1000)
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))
print(random.randint(1,10))

7
2
7
6


In [13]:
import numpy as np

In [14]:
np.random.rand()

0.25493823023335027

In [15]:
np.random.rand(2)

array([0.22676125, 0.88476722])

In [16]:
np.random.rand(2,4)

array([[0.12456946, 0.40779522, 0.92290492, 0.47403582],
       [0.58746868, 0.73503678, 0.94046416, 0.77386777]])

In [17]:
np.random.rand(4,2)

array([[0.3590264 , 0.17298182],
       [0.53829649, 0.26588628],
       [0.92897449, 0.15362251],
       [0.9074243 , 0.17436563]])

In [18]:
#help(np.random.rand)

In [19]:
from numpy.random import rand
rand(4,2)

array([[0.86993665, 0.69087122],
       [0.31919825, 0.45775122],
       [0.36453163, 0.56962301],
       [0.07079152, 0.665681  ]])

In [22]:
a = np.random.randn(2)
a

array([ 0.40561766, -1.84003281])

Array Indexing

In [25]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [26]:
data.ndim

1

In [27]:
data[0]

1

In [28]:
data[2]

3

In [29]:
data[[0,1]]

array([1, 2])

In [33]:
array1D = np.arange(50,100)
array1D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
array1D.shape

(50,)

In [35]:
array1D.ndim

1

In [36]:
array1D[-1]

99

In [38]:
array1D[49]

99

In [39]:
array1D[array1D.size -1]

99

In [40]:
array1D[9]

59

In [42]:
array1D[49]

99

In [43]:
array1D[-15]

85

In [44]:
array1D[[19,29,39,49]]

array([69, 79, 89, 99])

In [46]:
array1D[19],array1D[[29]],array1D[[39]],array1D[[49]]

(69, array([79]), array([89]), array([99]))

In [48]:
array2D = array1D.reshape(5,10)
array2D

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
array2D[0]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [51]:
array2D[1]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [53]:
array2D[[2,3]]

array([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [54]:
array2D[0,3]

53

In [57]:
array2D[[0,3]]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [58]:
array2D[[0]]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [61]:
array2D[[0,3,1,4,2]]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [62]:
array2D[3][1]

81

In [63]:
array2D[0,3]

53

In [64]:
array3D = array1D.reshape(5,5,2)
array3D

array([[[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]],

       [[70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89]],

       [[90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [65]:
array3D[0]

array([[50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59]])

In [66]:
array3D[0][2]

array([54, 55])

In [67]:
array3D[0,2,0]

54

slicing

In [69]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [70]:
data[0:2]

array([1, 2])

In [71]:
data[1:]

array([2, 3, 4])

In [72]:
data[-2:]

array([3, 4])

In [73]:
data[::]

array([1, 2, 3, 4])

In [74]:
data[::-1]

array([4, 3, 2, 1])

In [75]:
data[:-1:]

array([1, 2, 3])

In [76]:
data[-1:1:]

array([], dtype=int32)

In [77]:
data[:]

array([1, 2, 3, 4])

In [78]:
array1D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [80]:
array1D[0:10]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [82]:
array1D[2:10]

array([52, 53, 54, 55, 56, 57, 58, 59])

In [85]:
array1D[2:7]

array([52, 53, 54, 55, 56])

In [87]:
array1D[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

In [92]:
array1D[0:10][::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

D array slicing

In [93]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
data[0]

array([1, 2])

In [95]:
data[1]

array([3, 4])

In [97]:
data[[0,1]]

array([[1, 2],
       [3, 4]])

In [98]:
data[1:]

array([[3, 4],
       [5, 6]])

In [99]:
data[:2]

array([[1, 2],
       [3, 4]])

In [100]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
data[-1]

array([5, 6])

In [102]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [105]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
data[::-1]

array([[5, 6],
       [3, 4],
       [1, 2]])

To Do apply 3D concept

In [108]:
array2D

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
array2D.size

50

In [110]:
len(array2D)

5

In [111]:
len(array2D[0])

10

In [112]:
array2D[1:3]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [114]:
array2D[1:3, 3:6]

array([[63, 64, 65],
       [73, 74, 75]])

In [116]:
array2D[2:, :3]

array([[70, 71, 72],
       [80, 81, 82],
       [90, 91, 92]])

In [117]:
array2D

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
array2D[2:,3:]

array([[73, 74, 75, 76, 77, 78, 79],
       [83, 84, 85, 86, 87, 88, 89],
       [93, 94, 95, 96, 97, 98, 99]])

In [120]:
array2D[::, ::]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
array2D[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [123]:
array2D

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
array2D.shape

(5, 10)

In [4]:
data = np.array([[1,2],[3,4],[5,6]])
data

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
array2D

NameError: name 'array2D' is not defined

In [10]:
array2D = array2D.reshape(5,10)
array2D

NameError: name 'array2D' is not defined

In [11]:
array2D

NameError: name 'array2D' is not defined

In [13]:
array2D = array1D.reshape(5,10)
array2D

NameError: name 'array2D' is not defined